mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /var/data/mongo:/data/db

web:
    restart: always
    image: oktools/coypu
    working_dir: /quokka
    ports:
        - "80:5000"
    volumes:
        - .:/quokka
    links:
        - mongo:mongo
    command: sh etc/docker_wait_to_start.sh
    environment:
        - QUOKKA_MONGODB_HOST=mongo
        - WAIT_COMMAND=$(nc -zv mongo 27017)
        - WAIT_START_CMD=python manage.py runserver --host 0.0.0.0 --reloader --debug
        - WAIT_SLEEP=3
        - WAIT_LOOPS=50
    mem_limit: 1000000000

prompt:
    image: oktools/coypu
    working_dir: /quokka
    volumes:
        - .:/quokka
    links:
        - mongo:mongo
    environment:
        - QUOKKA_MONGODB_HOST=mongo
    mem_limit: 1000000000

pyshell:
    image: oktools/coypu
    working_dir: /quokka
    volumes:
        - .:/quokka
    links:
        - mongo:mongo
    command: python manage.py shell
    environment:
        - QUOKKA_MONGODB_HOST=mongo
        - WAIT_COMMAND=$(nc -zv mongo 27017)
        - WAIT_START_CMD=python manage.py shell
        - WAIT_SLEEP=2
        - WAIT_LOOPS=30
    mem_limit: 1000000000
